version: '3'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-time-zone='+9:00'"
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - "./.data/mysql:/var/lib/mysql"
      - "./ddl:/docker-entrypoint-initdb.d"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: on-failure

  migrate:
    image: migrate/migrate
    volumes:
      - "./db/migrations:/migrations"
    depends_on:
      mysql:
        condition: service_healthy
    command: "-path /migrations -database 'mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DATABASE}' up"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: "/work/src"
    command: "air -c .air.toml"
    volumes:
      - ".:/work/src"
    ports:
      - "8080:8080"
    environment:
      ENV: Development
      MYSQL_HOST: "mysql:3306"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: on-failure

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./docs/swagger.yaml:/data/openapi.yml
    environment:
      SWAGGER_JSON: /data/openapi.yml
    depends_on:
      - app

networks:
  new:
