services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: "/work/src"
    command: ["air", "-c", ".air.toml"]
    volumes:
      - ".:/work/src"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: on-failure
  