services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-time-zone='+9:00'"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    env_file:
      - db.env
    volumes:
      - "./.data/mysql:/var/lib/mysql"
      - "./ddl:/docker-entrypoint-initdb.d"
    restart: on-failure

  migrate:
    build:
      context: ./db
      dockerfile: Dockerfile
    depends_on:
      - mysql
    command: ["up"]
    environment:
      WAIT_HOSTS: db:3306
      MIGRATIONS_DIR: /migrations
    env_file:
      - db.env
    volumes:
      - ./db/migrations/migrations:/migrations

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: "/work/src"
    command: ["air", "-c", ".air.toml"]
    volumes:
      - ".:/work/src"
    ports:
      - "8080:8080"
    environment:
      ENV: Development
      MYSQL_HOST: "mysql:3306"
    env_file:
      - db.env
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: on-failure

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./docs/swagger.yaml:/data/openapi.yml
    environment:
      SWAGGER_JSON: /data/openapi.yml
    depends_on:
      - app
